import Head from "next/head";
import { SignInButton, useClerk, useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";
import FeatureFlagTable from "../components/FeatureFlagTable";
import { CreateNewFlagWizard } from "../components/CreateNewFlagWizard";

export default function Home() {
  const { isSignedIn, isLoaded: userLoaded, user } = useUser();
  const { signOut } = useClerk();

  const { data } = api.flags.getAll.useQuery();

  if (!userLoaded)
    return (
      <div className="flex min-h-screen flex-col items-center justify-center">
        Loading ...
      </div>
    );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center" data-theme="cupcake">
        <div className="min-w-[1024px] w-[1024px] flex max-w-full flex-col justify-stretch gap-4 p-4">
          {!isSignedIn && (
            <>
              <div>Please login:</div>
              <div className="flex justify-end gap-4 align-baseline">
                <SignInButton />
              </div>
            </>
          )}
          {isSignedIn && (
            <>
              <div>Welcome {user?.firstName ?? user?.username}!</div>
              <div className="flex justify-end gap-4 align-baseline">
                <button className="btn" onClick={() => void signOut()}>
                  Sign Out
                </button>
              </div>
              <div className="flex flex-col gap-4">
                {data && <FeatureFlagTable rows={data} />}
              </div>
              <CreateNewFlagWizard
                flagKeys={data ? data?.map(({ flag }) => flag.key) : []}
              />
            </>
          )}
        </div>
      </main>
    </>
  );
}
