import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";
import FeatureFlagTable from "../components/FeatureFlagTable";
import { Divider } from "@mui/material";
import Button from "@mui/material/Button";
import { CreateNewFlagWizard } from "../components/CreateNewFlagWizard";

export default function Home() {
  const { isSignedIn, isLoaded: userLoaded, user } = useUser();

  const { data } = api.flags.getAll.useQuery();

  if (!userLoaded)
    return (
      <div className="flex min-h-screen flex-col items-center justify-center bg-gray-100">
        Loading ...
      </div>
    );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-100">
        <div className="flex w-2/3 flex-col justify-stretch gap-4 p-4">
          {!isSignedIn && (
            <>
              <div>Please login:</div>
              <div className="flex justify-end gap-4 align-baseline">
                <Button variant="outlined">
                  <SignInButton />
                </Button>
              </div>
            </>
          )}
          {isSignedIn && (
            <>
              <div>Welcome {user?.firstName ?? user?.username}!</div>
              <div className="flex justify-end gap-4 align-baseline">
                <Button variant="outlined">
                  <SignOutButton />
                </Button>
              </div>
              <div className="flex flex-col gap-4">
                {data && <FeatureFlagTable rows={data} />}
              </div>
              <Divider />
              <CreateNewFlagWizard flagKeys={data ? data?.map(({ flag }) => flag.key) : []}/>
            </>
          )}
        </div>
      </main>
    </>
  );
}
